<a href="https://colab.research.google.com/github/carvestar/2024-intro-DA-code/blob/main/w02_3_python_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 패키지 numpy 개요와 자료형 ndarray

In [ ]:
import numpy as np

a = np.ndarray(shape=(2,2), dtype=int)
a

array([[3, 4],
       [5, 6]])

In [ ]:
import numpy as np

a = np.array([1, 2, 3], dtype = int)
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [ ]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [ ]:
a.data

In [ ]:
# 함수 array()의 인자는 배열을 표현하는 리스트나 튜플 하나이며 다음처럼 수를 나열하면 오류 발생
import numpy as np

np.array(1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
import numpy as np

unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [ ]:
lang = np.array(['파이썬', '자바', '씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [ ]:
lang = np.array(['파이썬', '자바', '씨'], dtype=str)
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [ ]:
a = np.array((1, 2, 3), dtype=float)
a

array([1., 2., 3.])

In [ ]:
b = np.array((1, 2.5, 3))
b

array([1. , 2.5, 3. ])

# 내장함수 arange()와 linspace()

In [ ]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [ ]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


배열 모양 바꾸는 reshape()

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
np.reshape(a, (3, 5)) # 차수에 따라 원소 수가 맞지 않으면 오류, (3, 5)면 원소 15개인데 원래 배열 원소는 12개이므로 오류

ValueError: cannot reshape array of size 12 into shape (3,5)

In [ ]:
# 2행 6열의 2차원 배열 반환
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
# 1차원 배열에서 3행 2열의 2차원 배열 반환
b = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# 1차원 배열에서 2행 3열의 2차원 배열 반환
np.reshape(b, (2, -1))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np

np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [ ]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [ ]:
print( (3 - 2) / (50 - 1) )

0.02040816326530612


In [ ]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 0.02)

In [ ]:
print( (3 - 2) / 50 )

0.02


In [ ]:
np.linspace(2.0, 3.0, num = 5, retstep = True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [ ]:
np.linspace(2.0, 3.0, num = 5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

In [ ]:
np.arange(0.1, 0.4, 0.1)

array([0.1, 0.2, 0.3, 0.4])

In [ ]:
np.arange(1, 4, 1) / 10.0

array([0.1, 0.2, 0.3])

In [ ]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [ ]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

# 내장함수 zeros()와 ones(), empty()

In [ ]:
# 원소가 모두 0인 배열을 생성하는 zeros()
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
np.zeros((5,), dtype = int)

array([0, 0, 0, 0, 0])

In [ ]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

In [ ]:
b.shape

(2, 1)

In [ ]:
# 원소가 모두 1인 배열을 생성하는 ones()
import numpy as np

np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import numpy as np

np.ones((2, 4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# 대각선 원소가 모두 1인 2차원 배열을 생성하는 eye()
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2, dtype = int)

array([[1, 0],
       [0, 1]])

In [ ]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a = np.eye(3, 4, -1)
a

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
# 원소가 모두 1인 배열을 생성하는 full()
# 모든 원소가 10인 2행 3열 2차원 배열
import numpy as np

np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
# 행이 모두 (1, 2, 3)인 2행 3열 2차원 배열
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
# 행이 모두 (0, 1, 2, 3)인 3행 4열 2차원 배열
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
# 모든 열이 0, 1, 2, 3인 4행 3열 2차원 배열
np.full([4, 3], fill_value = np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
# 원소 모두 1인 배열을 생성하는 empty(), 원소값 예측할 수 없음
import numpy as np

np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [ ]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [ ]:
np.empty([2, 3], dtype = int)

array([[  102265676175367,                 0,  -281225868672919],
       [10414754533146623, 16044069384683519,            -65460]])

In [ ]:
# 원소값이 0인 주어진 형태의 배열을 생성하는 zeros_like()
import numpy as np

a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# 원소값이 1인 주어진 형태의 배열을 생성하는 ones_like()
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

# 배열 연산

In [ ]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
# 배열과 스칼라 값과의 일반 연산은 모든 원소에 연산을 수행한 같은 모양의 배열 반환
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [ ]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [ ]:
# a = int, 저장값 = float -> 오류 발생, b += a는 실행 가능
a += b
a

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
b += a
b

array([0.5, 2.5, 4.5, 6.5])

In [ ]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [ ]:
a @ b

array([[12,  6],
       [12,  6]])

In [ ]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [ ]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [ ]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [ ]:
a.sum() # 배열의 모든 원소 합

46

In [ ]:
a.sum(axis = 0) # 동일 열에서 행을 순회해 세로로 더한 합의 배열

array([16, 30])

In [ ]:
a.sum(axis = 1) # 동일 열에서 행을 순회해 가로로 더한 합의 배열

array([30, 13,  3])

In [ ]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))

46
[16 30]
[30 13  3]


In [ ]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [ ]:
# 모든 원소 순서대로 누적 합계 반환
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [ ]:
import numpy as np

a = np.array([1, 4, 9])
np.sqrt(a)

array([1., 2., 3.])

In [ ]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [ ]:
import numpy as np

a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [ ]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [ ]:
np.add(a, b)

array([ 3,  6, 11])

In [ ]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [ ]:
np.power(a, b)

array([ 1, 16, 81])

# 배열 슬라이싱과 형태 수정

In [ ]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
print(a[3])
print(a[-2])

9
64


In [ ]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [ ]:
# [start:stop:step]의 슬라이싱으로 start > stop이면 오른쪽에서 왼쪽으로 step만큼 위치의 원소로 구성된 배열 반환

print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [ ]:
# 역순 배열
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [ ]:
a[::-2]

array([81, 49, 25,  9,  1])

In [ ]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [ ]:
# 슬라이싱의 대상이 원소 3개이므로 이에 맞는 배열 대입 가능
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [ ]:
# 따라서 2개 원소 배열 대입 불가능
a[2:5] = [-5, -5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [ ]:
b = np.array([5] * 10)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
b[::2] = -10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [ ]:
b[::2] = np.arange(5)
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

In [ ]:
# a = 5행 6열의 원소 30개의 2차원 배열
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
# 2차원 배열에서 a[i]는 첨자 i인 1차원 행 배열

In [ ]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [ ]:
# 2차원 배열 두 번째 첨자에 : 생략 가능
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[2:4] # a[i:j] = 첨자 i에서 j - 1까지

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[1:5:2] # 1행과 3행으로 구성된 2차원 배열

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[:, 1] # 모든 행에 대해 열의 첨자 1인 1차원 배열

array([ 1,  7, 13, 19, 25])

In [ ]:
a[:, 1:6] # 열 첨자 1에서 5까지의 2차원 배열

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [ ]:
a[:, ::2] # 열 첨자 0, 2, 4로 구성된 2차원 배열

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [ ]:
a[2, 4] # a[i, j] = 행 첨자 i, 열 첨자 j의 스칼라 값 반환

16

In [ ]:
a[2][4]

16

In [ ]:
a[1:3, 2:5] # 행 첨자 1, 2, 열 첨자 2, 3, 4로 구성되는 2차원 배열

array([[ 8,  9, 10],
       [14, 15, 16]])

In [ ]:
a[:, :] # 같은 배열 a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[::-1, ::-1] # 원 배열 a의 행과 열이 모두 바뀐 배열

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [ ]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# axis = 0인 첨자 1로 두 번째 (3, 4) 배열
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# axis = 0인 모든 배열에서 axis = 1의 첨자 1인 (2, 4) 모양 2차원 배열
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
# 위 반환 배열의 axis = 2의 첨자 1인 (1, 2) 모양 2차원 배열
a[:, 1, 1]

array([ 5, 17])

In [ ]:
# 배열의 axis = 2의 첨자 1인 (2, 3) 모양 2차원 배열
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
# ... = 해당되는 축(axis)이 모두 :임, a[..., 1] = a[:, :, 1]
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
# axis = 0의 첨자 1과 axis = 2의 첨자 1인 (3, ) 모양 1차원 배열
a[1, ..., 1]

array([13, 17, 21])

In [ ]:
# a[0, ...] = a[0, :, :]
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# a[0] = a[0, ...] = a[0, :, :]
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
# (a.size, ) 모양의 1차원 배열
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# np.transpose(a)와 a.transpose(), a.T = 행과 열을 바꾼 전치 배열 반환
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# 함수 np.tanspose(a, axes)와 같이 transpose() 함수는 옵션인 두 번째 인자가 있음
# 매개변수 axes는 지정된 경우 [0, 1, …, n-1]처럼 순열을 포함하는 튜플 또는 리스트여야 함
# 결과인 반환 배열의 i번째 축은 입력의 번호가 매겨진 axes[i] 축에 해당
# 지정하지 않으면 기본값은 range(a.ndim)[::-1]로 모든 축의 순서 바뀜
np.transpose(a, (0, 1))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a, (1, 0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
# 전치 행렬 반환
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [ ]:
# 원래 3차원 행렬 b 그대로 출력
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [ ]:
# 3차원 행렬 b에서 1축과 2축을 서로 바꾼 전치 행렬
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [ ]:
c = np.arange(1, 13).reshape(2, 2, 3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
c.transpose((1, 2, 0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [ ]:
np.transpose(c, (1, 2, 0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [ ]:
np.transpose(c)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [ ]:
# np.swapaxes(a, axis1, axis2) = 배열 a에서 axis1과 axis2를 서로 교환한 배열의 뷰를 반환
# 두 축만 교환 -> np.transpose()의 기능 부분적
# 새로운 배열 생성하지 않고 뷰만 반환 -> 뷰를 수정해도 원본 배열에 반영됨
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [ ]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [ ]:
y[0, 0] = 10
x

array([[10,  8,  9]])

In [ ]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [ ]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [ ]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [ ]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [ ]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [ ]:
org

array([  0,   1, 200,   3,   4])

In [ ]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [ ]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [ ]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [ ]:
org

array([0, 1, 2, 3, 4])

In [ ]:
# view의 base 속성은 원본 배열 반환 / 복사본의 base 속성은 None 반환
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [ ]:
y = x.reshape(2, 3) # view 반환
y

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y.base # 원본 배열 x 표시

array([0, 1, 2, 3, 4, 5])

In [ ]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [ ]:
c = z.copy()
print(c.base)

None


In [ ]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [ ]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [ ]:
# 개수가 다른 30, 40, 50으로 저장 불가능, 원본과 같은 개수의 값만 수정 가능
x[3:5] = [30, 40, 50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [ ]:
# 얕은 복사
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = a
b is a

True

In [ ]:
print(id(a))
print(id(b))

138045629823280
138045629823280


In [ ]:
print(b.base)

None


In [ ]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [ ]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [ ]:
print(id(a))
print(id(v))

138045629823280
138045629815120


In [ ]:
v[0, 1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [ ]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

# 브로드캐스팅

브로드캐스팅: Numpy가 산술 연산을 할 때 서로 다른 모양의 배열을 연산이 수행되도록 처리하는 방법

배열에 대한 요소별 산술을 수행할 수 있도록 모양이 다른 배열의 크기를 일치시키는 작업

In [ ]:
from numpy import array

a = array([3, 4, 5])
b = array([8, 7, 6])
a + b

array([11, 11, 11])

In [ ]:
# 두 배열의 모양이 애매하게 다르면 에러
from numpy import array

a = array([3, 4, 5, 7])
b = array([8, 7, 6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
from numpy import array

a = array([3, 4, 5])
a

array([3, 4, 5])

In [ ]:
b = 2
b

2

스칼라 2가 저장된 변수 b, 배열 a와 스칼라 b는 산술 연산 가능

내부적으로 스칼라 b가 브로드캐스트되어 연산이 수행되는 a와 같이 b 값이 그대로 3개의 원소가 된 배열

내부적으로 b = [2, 2, 2]로 브로드캐스트되어 연산 수행

브로드캐스트란 스칼라 b를 배열 a와 같은 모양의 배열이 되도록 늘리는 작업

In [ ]:
a + b

array([5, 6, 7])

In [ ]:
from numpy import array

A = array([[1, 2, 3], [1, 2, 3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
A + 2

array([[3, 4, 5],
       [3, 4, 5]])

In [ ]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = arange(-1, 2)
y

array([-1,  0,  1])

차원이 다른 위 두 배열 x, y를 사용해 산술 곱하기 연산 x * y 수행

배열 y를 2차원으로 그대로 아래쪽으로 브로드캐스트(전파)해 늘리면 배열 x와 y는 모양이 (3, 3)으로 같아 산술 연산 가능해짐

In [ ]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [ ]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [ ]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [ ]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [ ]:
from numpy import arange

x = arange(1, 4)
x

array([1, 2, 3])

In [ ]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [ ]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [ ]:
x - y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [ ]:
from numpy import arange

x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [ ]:
y = arange(1, 3)
y

array([1, 2])

In [ ]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [ ]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [ ]:
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [ ]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [ ]:
a = x[np.newaxis, :]
a

array([[1, 2, 3]])

In [ ]:
a = x[:, np.newaxis]
a

array([[1],
       [2],
       [3]])

In [ ]:
from numpy import array

b = array([1, 2, 3])
b

array([1, 2, 3])

In [ ]:
a + b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
a * b

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

# 고급 색인

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [ ]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [ ]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [ ]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [ ]:
# 색인 값이 범위를 벗어나면 오류
x[np.array([10])]

NameError: name 'x' is not defined

In [ ]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0, 1]

1

In [ ]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[[0], [1]]

array([1])

In [ ]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [ ]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x[[1, 3], [2, 2]]

array([10, 26])

In [ ]:
x[[1, 3], [2]]

array([10, 26])

In [ ]:
x[[1, 3], [3, 3]]

array([11, 27])

In [ ]:
x[[1, 3], [3]]

array([11, 27])

In [ ]:
# 브로드캐스팅이 될 수 없는 형태인 모양 (3, )과 모양 (2, )이면 오류
from numpy import array

x[array([0, 2, 4]), array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [ ]:
x[np.array([0, 2, 4]), 1]

array([ 1, 17, 33])

In [ ]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


In [ ]:
from numpy import arange

a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
# 고급 색인
a[arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [ ]:
a[arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [ ]:
a[arange(2, 5)][:, arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])